---
title: "Splines"
author: "Igor Adamiec"
date: "8/29/2019"
output: html_document
---

```{r}
library(splines)
```

```{r}
fit <- lm(wage~bs(age, knots = c(25, 40, 60)), data = Wage)
pred <- predict(fit, newdata = list(age = age.grid), se = T)
plot(age, wage, col = "gray")
lines(age.grid, pred$fit, lwd = 2)
lines(age.grid, pred$fit + 2*pred$se.fit, lty = "dashed")
lines(age.grid, pred$fit - 2*pred$se.fit, lty = "dashed")
```

```{r}
dim(bs(age, knots = c(25, 40, 60)))
dim(bs(age, df = 6))
attr(bs(age, df = 6), "knots")
```

# Natural splines

```{r}
fit2 <- lm(wage~ns(age, df=4), data = Wage)
pred2 <- predict(fit2, newdata = list(age = age.grid), se = T)
plot(age, wage, col = "gray", cex = .5)
lines(age.grid, pred2$fit, lwd = 2)
```

# smoothing splines

```{r}
fit <- smooth.spline(age, wage, df = 16)
fit2 <- smooth.spline(age, wage, cv = T)
```

```{r}
fit2$df
fit2$lambda
```

```{r}
plot(age, wage, xlim = agelims, cex = .5, col = "darkgrey")
title("Smoothing Spline")
lines(fit, col = "red", lwd = 2)
lines(fit2, col = "blue", lwd = 2)
legend("topright", legend = c("16 DF", "6.8 DF"),
       col = c("red", "blue"), lty = 1, lwd = 2, cex = .8)
```

# Local regression

```{r}
fit <- loess(wage~age, span = .2, data = Wage)
fit2 <- loess(wage~age, span = .5, data = Wage)
```

```{r}
ggplot() +
  geom_point(data = Wage, aes(x = age, y = wage), size = .5) +
  geom_line(aes(x = age.grid, y = predict(fit, newdata = tibble(age = age.grid))),size = 1, color = "red") +
  geom_line(aes(x = age.grid, y = predict(fit2, newdata = tibble(age = age.grid))), size = 1, color = "blue")
```




























