---
title: "ROC Curves"
author: "Igor Adamiec"
date: "9/18/2019"
output: html_document
---

```{r}
library(ROCR)
library(yardstick)
```

```{r}
rocplot <- function(pred, truth, ...) {
  predob <- prediction(pred, truth)
  perf <- performance(predob, "tpr", "fpr")
  plot(perf, ...)
}
```

```{r}
svmfit.opt <- svm(y~., data = dat[train,], kernel = "radial",
                  gamma = , cost = 1, decision.values = T)
fitted <- attributes(predict(svmfit.opt, dat[train,], decision.values = T))$decision.values
```

```{r}
par(mfrow = c(1,2))
rocplot(fitted, dat[train, "y"], main = "Training Data")
```

```{r}
roc_curve(tibble(truths = dat[train,]$y,est_1 = (attributes(predict(svmfit.opt,dat[train,], decision.values = T))$decision.values)[,1],
                 est_2 = attributes(predict(svmfit.flex, dat[train,], decision.values = T))$decision.values[,1]), truth = truths, est_2) %>% 
  autoplot()
```

```{r}
par(mfrow = c(1,2))
svmfit.opt <- svm(y~., data = dat[train,], kernel = "radial",
                  gamma = , cost = 1, decision.values = T)
fitted <- attributes(predict(svmfit.opt, dat[train,], decision.values = T))$decision.values
rocplot(fitted, dat[train, "y"], main = "Training Data")
svmfit.flex <- svm(y~., data = dat[train,], kernel = "radial",
                   gamma = 50, cost = 1, decision.values = T)
fitted <- attributes(predict(svmfit.flex, dat[train,], decision.values = T))$decision.values
rocplot(fitted, dat[train, "y"], add = T, col = "red")
```

```{r}
roc_curve(tibble(truths = dat[-train,]$y,est_1 = (attributes(predict(svmfit.opt,dat[-train,], decision.values = T))$decision.values)[,1],
                 est_2 = attributes(predict(svmfit.flex, dat[-train,], decision.values = T))$decision.values[,1]), truth = truths, est_2) %>% 
  autoplot()
```



