---
title: "Support Vector Classifier"
author: "Igor Adamiec"
date: "9/10/2019"
output: html_document
---

```{r}
library(e1071)
library(tidyverse)
```

```{r}
set.seed(1)
x <- matrix(rnorm(20*2), ncol = 2)
y <- c(rep(-1, 10), rep(1, 10))
x[y==1,]=x[y==1, ] + 1
plot(x, col = (3-y))
```

```{r}
dat <- data.frame(x = x, y = as.factor(y))
svmfit <- svm(y~., data = dat, kernel = "linear", cost = 10, scale = F)
plot(svmfit, dat)
```

```{r}
svmfit$index
```

```{r}
svmfit %>% 
  summary()
```

```{r}
svmfit <- svm(y~., data = dat, kernel = "linear", cost = .1, scale = F)
plot(svmfit, dat)
svmfit$index
```

```{r}
set.seed(1)
tune.out <- tune(svm, y~., data = dat, kernel = "linear",
                 ranges = list(cost = c(.001, .01,.1, 1, 5, 10, 100)))

tune.out %>% 
  summary()
```

```{r}
best.mod <- tune.out$best.model

best.mod %>% 
  summary()
```

```{r}
xtest <- matrix(rnorm(20*2), ncol = 2)
ytest <- sample(c(-1, 1), 20, rep = T)
xtest[ytest == 1, ] = xtest[ytest == 1, ] + 1
testdat <- data.frame(x = xtest, y = as.factor(ytest))
ypred <- predict(best.mod, testdat)
table(truth = testdat$y, predict = ypred)
```

```{r}
svmfit <- svm(y~., data = dat, kernel = "linear", cost = .01,
              scale = F)
ypred <- predict(svmfit, testdat)
table(truth = testdat$y, predict = ypred)
```

```{r}
x[y == 1, ] = x[y == 1, ] + .5
plot(x, col = (y + 5)/2, pch = 19)
```

```{r}
dat <- data.frame(x = x, y = as.factor(y))
svmfit <- svm(y~., data = dat, kernel = "linear", cost = 1e+05)
svmfit %>% summary()
```

```{r}
svmfit <- svm(y~., data = dat, kernel = "linear", cost = 1)
svmfit %>% summary()
plot(svmfit, dat)
```



























